# Generated by Django 4.2.7 on 2023-12-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_quantity_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
