# Generated by Django 4.2.7 on 2023-12-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_created_at_order_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
