# Generated by Django 4.2.7 on 2023-12-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='placecd_at',
            new_name='placed_at',
        ),
    ]
