# Generated by Django 4.2.7 on 2023-12-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total',
        ),
    ]
