# Generated by Django 4.2.7 on 2023-12-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_total_price_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_price',
        ),
    ]
