# Generated by Django 4.2.7 on 2023-12-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
