# Generated by Django 4.2.7 on 2023-12-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_rename_price_orderitem_individual_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='individual_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
