# Generated by Django 4.2.7 on 2023-12-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_cartitem_individual_price_cartitem_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='individual_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total_amount',
        ),
    ]
