# Generated by Django 4.2.7 on 2023-12-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_cart_id_alter_cartitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order_item',
        ),
    ]
